src/components/drawer/drawer.stories.js
=> fix: Drawer Body Content get shifted to the right edge

src/components/cards/list-blocks.stories.tsx
Aligned the cards' inner content.
https://bsf.d.pr/v/ugNsvO
Bug fix
https://bsf.d.pr/v/ugNsvO
-   [x] I've created the npm build.
-   [x] My code follows accessibility standards 
-   [x] I've included any necessary tests 
-   [x] I've included developer documentation 
=> Alignment fixed for Cards

.github/workflows/storybook-deployment.yml, src/components/sidebar/sidebar.tsx, src/utilities/functions.js
=> SUR-356 - Sidebar bug with 'use client;'

src/components/dropdown-menu/dropdown-menu.stories.tsx, src/components/dropdown-menu/dropdown-menu.tsx, src/components/dropdown-menu/dropdown-types.ts
=> SUR-358 - fix: z-index of the DropdownMenu component is not overridable

src/components/line-chart/line-chart.tsx
=> fix: Removed line chart default margin

changelog.txt, src/components/input/input.stories.tsx, src/components/input/input.tsx, src/components/label/label.tsx
=> Fix: Asterisk missing on required input label.

src/components/table/table.tsx
=> fix: Divider between table body and footer not visible

src/components/checkbox/checkbox.tsx, src/components/radio-button/styles.ts, src/components/select/select.tsx, src/components/switch/switch.tsx
=> SRML-64 - fix: Focus ring offset

changelog.txt, src/components/datepicker/datepicker-component.tsx, src/components/datepicker/datepicker.tsx, src/components/table/table.tsx
=> Updated the change log and fix datepicker component UI

.github/workflows/code-analysis.yml
Starting February 1st, 2025, we are closing down v1-v2 of [actions/cache](https://app.github.media/e/er?s=88570519&lid=6814&elqTrackId=a3bc821626b94473987e2c1b05d7f97a&elq=10f83758259c4978bc05f8e76cef0b5b&elqaid=4282&elqat=1&elqak=8AF5A5B4BDB0473BC910C050E532EFF49739ECE0FD8F8C905FB5DED5D1CABD7EC8F8) (read more about it in this [changelog announcement](https://app.github.media/e/er?s=88570519&lid=6815&elqTrackId=08a5e2ee0de44b669cfee44c72a218f2&elq=10f83758259c4978bc05f8e76cef0b5b&elqaid=4282&elqat=1&elqak=8AF5E7AAA12E3C7C230E5849DC6FF5707A50ECE0FD8F8C905FB5DED5D1CABD7EC8F8)) as well as all previous versions of the @actions/cache package in actions/toolkit. Attempting to use a version of the @actions/cache package or actions/cache after the announced deprecation date will result in a …
=> Updating cache package

src/components/bar-chart/bar-chart.stories.tsx, src/components/bar-chart/bar-chart.tsx
https://d.pr/v/triQSY
You can use Y axis tick formatter like below
```jsx
<BarChart
yTickFormatter={
( value ) => value ? value : 'n/a'     }
/>
```
=> SUR-305 - Added Y Axis tick formatter

changelog.txt, package-lock.json, src/components/datepicker/datepicker.stories.tsx, src/components/datepicker/datepicker.tsx
**Demo** - https://d.pr/v/kdIvjr
Fix - Show active in preset with background of Date picker. 
=> SUR-384 - Added - show active preset of datepicker

changelog.txt, src/components/select/select-types.ts, src/components/select/select.tsx, src/utilities/hooks.ts
=> Customize select component search functionality

src/components/select/select.tsx
=> fix: Showing React.Memo instead of the component name

changelog.txt, src/components/switch/switch.tsx, src/theme/default-config.js
=> Add inner shadow to the disabled switch

changelog.txt, package.json, src/components/button/button.tsx, src/components/switch/switch.tsx, src/theme/default-config.js, vite.config.ts
- New - Added new size 'xs' to the Switch component.
- Fixed - Undefined JSX error when @wordpress/scripts version is above 28.
- Fixed - Tree shaking not working.
- Improvement - Update destructive button ring color.
=> SUR-429, SUR-430, SUR-431 - Compatibility fixes and component improvements

src/components/radio-button/radio-button.stories.tsx, src/components/radio-button/radio-button.tsx
=> SUR-429, SUR-430, SUR-431 - style: Update Radio button padding and gap

src/components/radio-button/radio-button.tsx
=> SUR-429, SUR-430, SUR-431 - fix: Gap between label and description of Radio Button

src/components/file-preview/file-preview.stories.tsx
=> fix (Story): Input value not reset after removing selected file

changelog.txt, src/components/area-chart/area-chart.tsx, src/components/tabs/tabs.tsx
```
- Improvement - Introduced the `areaChartWrapper` prop in the AreaChart component to allow for better customization options.
- Improvement - Removed the group selector from the Tabs component to simplify style overrides.
```
=> Tabs and Area chart component improvements

changelog.txt, src/components/sidebar/sidebar.stories.tsx, src/components/sidebar/sidebar.tsx
- Add an additional prop to handle the default collapse state when the sidebar is not collapsible.
- https://d.pr/v/c6H6Hh
=> SUR-448 - [Force UI] SideBar component improvements

src/components/area-chart/area-chart.stories.tsx, src/components/area-chart/area-chart.tsx, src/components/line-chart/line-chart.stories.tsx, src/components/line-chart/line-chart.tsx, src/components/text/text.stories.tsx
- Added a prop to customize y-axis colors.
- Updated the biaxial line chart story.
- Add y-axis tick formater.
- https://d.pr/i/nhiKfD
=> imprv (LineChart): Prop to customize y-axis colors

src/components/editor-input/editor-input-style.ts
=> Remove default list style from the dropdown menu

changelog.txt, src/components/accordion/accordion.tsx
- https://d.pr/v/FDQNbp
- fix: Incorrect build extensions.
- fix: Dropdown not visible when the accordion state is open.
=> SUR-476 - [Smart Tag Dropdown] Please fix the Smart Tag value dropdown in Meta sidebar
