brainstormforce/force-ui

src/components/switch/switch.stories.js

Add Storybook story for Switch component

SUR-259 Add Stories - Switch component (SUR-260)

---

src/components/switch/switch.stories.js

fix: ensure defaultValue works correctly in Switch Storybook stories

SUR-260 Switch Component Storybook stories (Fix defaultValue)

---

src/components/button/button.jsx
src/components/label/label.jsx
src/components/tooltip/readme.md
src/components/tooltip/tooltip.stories.js

SUR-277 Molecule: Implement Tooltip with label/icon

---

src/components/select/select-atom.stories.jsx

SUR-295 - Added Select Story

---

src/components/progress-steps/progress-steps.stories.jsx

SUR-288 - ProgressSteps story fix

---

src/components/container/container-item.stories.jsx
src/components/container/container.stories.jsx

SUR-288 - Added separate story for container.item

---

src/components/progress-steps/progress-steps.stories.jsx

ProgressSteps Story Control Descriptions Added

---

src/components/menu-item/menu.stories.js

Menu Item Name FIxes

---

src/components/topbar/topbar.stories.js

SUR-280 Topbar displayName fixed

---

package-lock.json
src/components/progress-steps/progress-steps.stories.jsx
src/components/select/select-atom.stories.jsx
src/components/select/select.stories.js
src/components/sidebar/sidebar.jsx
src/components/tabs/tabs.stories.jsx

Tabs story displayName fix

---

src/components/topbar/topbar.jsx
src/components/topbar/topbar.stories.js

Fix Topbar overflow issue

---

src/components/toaster/toaster.stories.jsx

toaster fixes - code not rendering onClick function code in 'show code'

---

.storybook/preview-head.html

fix: Font family of the Storybook

---

src/components/progress-steps/progress-steps.jsx
src/components/progress-steps/progress-steps.stories.jsx
src/components/progress-steps/readme.md

Progress Steps Line min-width fix

---

src/components/progress-steps/progress-steps.jsx

line spacing fixes issue if no labelText

---

src/components/tooltip/readme.md
src/components/tooltip/tooltip.jsx
src/components/tooltip/tooltip.stories.js

Ability to add custom jsx - title, description, button

SUR-306 Tooltip: Ability to add custom jsx - title, description, button

---

src/components/sidebar/sidebar.jsx

Added Tooltip changes in Sidebar

---

src/components/radio-button/radio-button.jsx

added uat changes
Radio Button click fix  - done
Radio center icon not centered - https://bsf.d.pr/i/hl085y - fixed
Radio icon clicked not getting clicked. done
https://d.pr/v/EC11TU

SUR-310 - Uat feedback menu

---

src/components/editor-input/editor-input.jsx
src/components/editor-input/editor-input.stories.jsx
src/components/editor-input/mention-plugin/mention-component.jsx
src/components/editor-input/mention-plugin/mention-plugin.jsx
src/components/editor-input/readme.md
src/components/menu-item/menu-item.jsx
src/components/toaster/utils.jsx

SUR-312 - UAT feedback - Editor input space issue

---

src/components/editor-input/editor-input.stories.jsx
src/components/editor-input/mention-plugin/mention-component.jsx

- https://share.cleanshot.com/c2hkcMD7

fix: Loosing focus when pressing arrow key with mention node in the editor

---

src/components/badge/badge.jsx
src/components/button/button.jsx
src/components/cards/list-blocks.stories.jsx
src/components/cards/plugin-blocks.stories.jsx
src/components/cards/widget-blocks.stories.jsx
src/components/dropdown-menu/dropdown-menu.jsx
src/components/editor-input/editor-input-style.js
src/components/editor-input/editor-input.stories.jsx
src/components/input/input.jsx
src/components/sidebar/sidebar.stories.js
src/components/textarea/textarea.jsx
src/templates/dashboard-astra/dashboard-astra.stories.js
src/templates/dashboard-spectra/dashboard-spectra.stories.js
src/templates/onboarding-backup/onboarding-backup.stories.js
src/templates/onboarding-connect/onboarding-connect.stories.js
src/templates/onboarding-done/onboarding-done.stories.js
src/templates/onboarding-email-smtp/onboarding-smtp-connect.stories.js
src/templates/onboarding-import/onboarding-import.stories.js
src/templates/onboarding-profile/onboarding-profile.stories.js
src/templates/onboarding-setup-done/onboarding-setup-done.stories.js
src/templates/onboarding-setup-tools/onboarding-setup-tools.stories.js
src/templates/onboarding-social/onboarding-social.stories.js
src/templates/onboarding-spam/onboarding-spam.stories.js

SUR-310 - UAT fixes

---

src/components/cards/widget-blocks.stories.jsx
src/components/editor-input/editor-input.stories.jsx
src/components/radio-button/radio-button.jsx
src/templates/dashboard-astra/dashboard-astra.stories.js
src/templates/dashboard-spectra/dashboard-spectra.stories.js
src/templates/onboarding-backup/onboarding-backup.stories.js
src/templates/onboarding-import/onboarding-import.stories.js
src/templates/onboarding-setup-tools/onboarding-setup-tools.stories.js

Removed border for radio buttons
Removed border for radio buttons in all blocks ( story level )

Uat feedback radio

---

src/templates/onboarding-done/onboarding-done.stories.js
src/templates/onboarding-import/onboarding-import.stories.js

adjusted gaps
https://d.pr/i/tcTWuT

spaces adjusted for button

---

src/templates/dashboard-spectra/dashboard-spectra.stories.js

Removed commented code in Template Dashboard Spectra

---

.github/workflows/chromatic.yml
.github/workflows/storybook-deployment.yml
package-lock.json
package.json
src/templates/admin-settings-SureRank/admin-settings-SureRank.stories.js

This will deploy on github pages.
https://brainstormforce.github.io/force-ui/
New Feature
See the actions passed in Github actions after merging in master.
-   [x] I've created the npm build.
-   [x] My code has proper inline documentation 
-   [x] I've included developer documentation 

GitHub deployment

---

src/components/cards/list-blocks.stories.jsx
src/components/cards/widget-blocks.stories.jsx
src/components/title/title.jsx
src/templates/dashboard-astra/dashboard-astra.stories.js
src/templates/dashboard-spectra/dashboard-spectra.stories.js
src/templates/onboarding-backup/onboarding-backup.stories.js
src/templates/onboarding-setup-tools/onboarding-setup-tools.stories.js
src/templates/onboarding-spam/onboarding-spam.stories.js

Added xxs for badge, Title sizes modified
https://d.pr/v/kp1IU6
https://d.pr/i/0byuAU

SUR-310 - added uat changes radio, title

---

src/components/cards/plugin-blocks.stories.jsx
src/components/cards/widget-blocks.stories.jsx
src/ui/icons.js

Icon size, badge

---

src/components/editor-input/mention-plugin/mention-component.jsx

SUR-310 - Remove the Editor Input components  left margin from the badge

---

src/components/radio-button/radio-button.jsx
src/components/sidebar/sidebar.jsx
src/components/tooltip/readme.md
src/components/tooltip/tooltip.jsx
src/components/tooltip/tooltip.stories.js
src/templates/admin-settings-SureRank/admin-settings-SureRank.stories.js

Tooltip fixes - reverted title and content props

---

src/components/switch/switch.jsx

- https://brainstormforce.slack.com/archives/C0783G47NGK/p1729086121988599?thread_ts=1729080590.854039&cid=C0783G47NGK
- https://brainstormforce.slack.com/archives/C0783G47NGK/p1729085933481239?thread_ts=1729080590.854039&cid=C0783G47NGK
NA
UAT feedback
http://localhost:6006/?path=/docs/atoms-switch--docs
-   [x] I've created the npm build.
-   [x] My code follows accessibility standards 
-   [x] My code has proper inline documentation 

SUR-310 - Switch fixes

---

src/components/alert/alert.stories.js
src/components/select/component-style.js
src/components/select/select.jsx

Select Atom: Changed the select atom font size ( placeholder and options)
https://d.pr/v/aj1pmR
Select Molecule: Changed the height auto. So that it will not show any empty space. 
https://d.pr/v/ZJuF8o
Alert Atom: Changed button type to link from button in alert
https://d.pr/i/ECqtEv

SUR-310 - alert button type change, and select text size change

---

src/components/tabs/tabs.stories.jsx

SUR-310 - Tabs Story Improvement

---

src/components/pagination/component-style.js
src/components/pagination/pagination.jsx
src/components/pagination/pagination.stories.js

Video: https://bsf.d.pr/v/LHbESt

SUR-232 Implement Pagination Component in Force UI as per Figma - Fixed tab accessibility issues

---

src/components/search/search.jsx
src/utilities/functions.js

Video: https://bsf.d.pr/v/dZ7Uzl

SUR-223 Implement Search Component in Force UI as per Figma - Fixed accessibility issues

---

src/components/drawer/drawer.jsx
src/components/select/readme.md
src/components/select/select-atom.stories.jsx
src/components/select/select.jsx
src/components/select/select.stories.js

SUR-322 - Select issue with Drawer component

---

package-lock.json
src/components/button/button.stories.tsx
src/components/button/button.tsx
src/components/cards/list-blocks.stories.tsx
src/components/cards/plugin-blocks.stories.tsx
src/components/cards/widget-blocks.stories.tsx
src/templates/admin-settings-Spectra/admin-settings-Spectra.stories.jsx
src/templates/admin-settings-SureCart/admin-settings-SureCart.stories.jsx
src/templates/admin-settings-SureRank/admin-settings-SureRank.stories.jsx
src/templates/dashboard-astra/dashboard-astra.stories.jsx
src/templates/dashboard-spectra/dashboard-spectra.stories.jsx

Added code structure changes in storybook.
https://d.pr/v/2vrkgH

Added code structure changes

---

src/components/cards/list-blocks.stories.tsx
src/components/cards/widget-blocks.stories.tsx
src/components/radio-button/radio-button.tsx
src/components/radio-button/styles.ts
src/templates/dashboard-astra/dashboard-astra.stories.jsx
src/templates/dashboard-spectra/dashboard-spectra.stories.jsx

Added card radio issue fix
https://d.pr/i/MYB7kF

Added card radio issue fix

---

src/components/progress-steps/progress-steps.stories.tsx

Steps width issue fixed
https://d.pr/i/9WvZnr

Steps width issue fixed

---

src/components/accordion/accordion.tsx

Fixed Chevron icon size for Accordion component

Fixed Chevron icon size for Accordion component

---

src/components/input/input.tsx
src/components/menu-item/menu-item.tsx

- Added color transition to the input component.
- Fix: Arrow is not visible when showArrowOnHover is false.

Minor UI fixes

---

package-lock.json
src/components/datepicker/datepicker-component.tsx
src/components/datepicker/datepicker.stories.tsx
src/components/datepicker/datepicker.tsx
src/components/datepicker/readme.md

Added onDateSelect and onApply in normal variant.
Added onDateSelect in dualdate and presets
https://d.pr/v/brl7KF

Datepicker Fixes

---

src/components/dropzone/dropzone.stories.tsx
src/components/dropzone/dropzone.tsx
src/components/dropzone/index.ts
src/components/index.ts
src/components/loader/loader.tsx
src/components/search/search.tsx
src/utilities/functions.js

Added Dropzone component
https://d.pr/v/SF3oYt

SUR-228 Dropzone

---

src/components/dropzone/dropzone.tsx

Image height overflow issue
https://d.pr/v/97hpPW

preview image height issue

---

src/components/pagination/pagination.tsx
src/components/table/table.tsx

- Fix: Table Checkbox column width
- Fix: Pagination component Doc.

fix: Table Checkbox column width

---

src/components/line-chart/line-chart.tsx
src/components/table/table.tsx

- Fix Line chart responsive design.
- Fix Table component responsive design.

fix: Line chart and Table component responsive issues

---

src/components/select/component-style.ts

SRML-64 - fix: Select combobox search icon size

---

src/components/checkbox/checkbox.tsx
src/components/label/label.tsx
src/components/switch/switch.tsx

SRML-64 - fix: Clicking on the hint text toggles checkbox/switch and updated help text font-size

---

src/components/datepicker/datepicker.tsx

fix: DatePicker component presets button width

---

changelog.txt
src/components/badge/badge.tsx
src/components/drawer/drawer-body.tsx
src/components/drawer/drawer-footer.tsx
src/components/drawer/drawer-header.tsx
src/components/drawer/drawer-panel.tsx
src/components/drawer/drawer.tsx
src/components/select/select.stories.tsx

- Update the flyout design based on the new mockup.
- Added a new prop to the Badge component to disable hover effect.
- https://d.pr/i/D61Y97

SRML-64 - Update the flyout design based on the new mockup

---

.github/workflows/code-reviewer.yml

Created workflow for code review

---

changelog.txt
src/components/radio-button/radio-button.tsx

fix: Radio button ring width

---

src/components/file-preview/file-preview.stories.tsx
src/components/file-preview/file-preview.tsx

fix: FilePreview component accessibility issues

---

src/components/search/search.stories.tsx

fix: Search-box story test fails

---

changelog.txt
src/components/checkbox/checkbox.tsx
src/components/radio-button/radio-button.tsx
src/components/switch/switch.tsx
src/theme/default-config.js

SUR-449 - Add RTL support to the Switch, Checkbox, and RadioButton components

---

changelog.txt
src/components/area-chart/area-chart.tsx

improvement (Area chart) : Display xAxis data on the tooltip when hovering

---

changelog.txt
src/components/dropzone/dropzone.tsx
src/components/toaster/utils.tsx

- Add className prop to the dropzone for customization.
- Resolved toaster content overflow issue.

Dropzone and Toaster component improvements

---

src/templates/admin-settings-Spectra/admin-settings-Spectra.stories.jsx

Update the `Admin Settings - Spectra` template

---

changelog.txt
src/components/select/component-style.ts
src/components/select/select.tsx

improvement (Atom: Select) - Update the Select component empty state message font-size

---

changelog.txt
src/components/editor-input/mention-plugin/mention-component.tsx

SUR-533 - Mockup Inputs
